### ISSUE TITLE
Reduce number of parentheses (), feature request

### ISSUE THREAD

**Issue by PhilAndrew** [lihaoyi/Scalite#6]
Hi! I'm using Scalite now for my Scala programming.

I'd like the " paren-less syntax" to increase to reduce the number of parentheses, expanding your section on "Light syntax", or can you suggest where I can change the code to do it myself?

This:
class Point xc: Int, yc: Int
becomes:
class Point(xc: Int, yc: Int) 

This:
def move(dx: Int, dy: Int) =  
becomes:
def move dx: Int, dy: Int =  

This:
val rectangle = new Rectangle 20, 20, 100, 100
becomes:
val rectangle = new Rectangle(20, 20, 100, 100)

**Comment by yawaramin** [comment]
OK to close this?
